### PR TITLE
Change SchnorrProof to follow the 1.51 spec

### PR DESCRIPTION
**Pull request by JohnLCaron**
Move Guardian committments to SchnorrProof.publicKey, issue #62.
This simplifies the KeyCeremony and the Guardian class and proto.
Also implement the 1.51 change of #147, v_ij = (ui,j − ci,j * ai,j ) mod q.
This allows isValid() to use a multiplication instead of a division.

### CODE REVIEW

**Comment by danwallach** [comment]
My only real concern here is that the public key is now part of the Schnorr proof, rather than being held outside, as beforehand.

**Comment by JohnLCaron** [comment]
> public key is now part of the Schnorr proof

I thought it was slightly better, see issue #62. 

Everywhere we use a Guardian's SchnorrProof, we also need the Guardian's coefficientCommitments. By putting them together, it makes the code slightly simpler. Basically we combine these two:

````
    /** The public coefficient commitments `K_j = g^a_j`. */
    val coefficientCommitments: List<ElementModP>,

    /** A public proof of possession for each secret coefficient. */
    val coefficientProofs: List<SchnorrProof>,
````
which  eliminates a possible mismatch between the two. Theres no extra serialization, its exactly the same.

This also follows spec 1.51, section 4.5.1. Not that thats definitive, we dont follow their serialization all the time.

**Comment by JohnLCaron** [comment]
> Also, BTW, there's a lot going on in this PR. Makes it harder to review the whole shebang.

Apologies, I should have separated out the change to the challenge formula.
Ill try to keep that cleaner, esp if I know you want to review it.

**Comment by danwallach** [comment]
Ok. I'll say "good for now", knowing that we're getting revisions to the key sharing coming soon, so we'll have major changes happening here later on.

**Pull request merged**
